
spring:
  application:
    name: wallet-grpc-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    hikari:
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: false
    properties:
      hibernate:
        cache:
          use_second_level_cache: false
        connection:
          provider_disables_autocommit: true
        jdbc:
          batch_size: 5
          fetch_size: 5
      order_inserts: true
      order_updates: true
      query:
        in_clause_parameter_padding: true
        fail_on_pagination_over_collection_fetch: true
    show-sql: true


grpc:
  server:
    port: 8080